name: Install dependencies

description: Install default dependencies
inputs:
  exact-prod:
    default: false
    description: Install exact version for production dependencies
    required: true

runs:
  using: composite
  steps:
    - id: prepare
      name: Prepare
      run: echo has-eslint=`if [ -f ./.eslintrc.react.yml ]; then echo true; else echo false; fi` >> $GITHUB_OUTPUT
      shell: bash

    - name: Run npm install for production
      run: npm install --save react@latest react-dom@latest
      shell: bash

    - name: Run npm install for development
      run: npm install --save-dev ${{ inputs.exact-prod && '--save-exact' || '' }} concurrently@latest esbuild@latest eslint@latest eslint-plugin-prettier@latest eslint-plugin-react@latest typescript@latest @types/react@latest @types/react-dom@latest @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest
      shell: bash

    - continue-on-error: true
      name: Run npm audit fix
      run: npm audit fix
      shell: bash

    - id: get-versions
      name: Get versions
      run: echo react-version=`npm ls react --json | jq -r '.dependencies.react.version'` >> $GITHUB_OUTPUT
      shell: bash

    - if: ${{ steps.prepare.outputs.has-eslint == 'true' }}
      name: Set React version in `.eslintrc.react.yml` to ${{ steps.get-versions.outputs.react-version }}
      run: |
        docker run -i --rm mikefarah/yq '.settings.react.version = "${{ steps.get-versions.outputs.react-version }}"' < ./.eslintrc.react.yml > ./.eslintrc.react.yml.tmp
        mv .eslintrc.react.yml.tmp .eslintrc.react.yml
        ls .eslintrc.react.yml
      shell: bash

    - name: Summary
      run: |
        echo \`\`\`json >> $GITHUB_STEP_SUMMARY
        cat package.json | jq '{ dependencies: .dependencies, devDependences: .devDependencies }' >> $GITHUB_STEP_SUMMARY
        echo \`\`\` >> $GITHUB_STEP_SUMMARY
