name: Build pages

description: Build and upload pages

runs:
  using: composite
  steps:
    - name: Checkout
      shell: bash
      uses: actions/checkout@v3
    - name: Setup Pages
      shell: bash
      uses: actions/configure-pages@v2
    - name: Clean install
      run: npm ci
      shell: bash
    - name: Build
      run: npm run build
      shell: bash
    - name: Upload artifact
      shell: bash
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public
