name: Bump dependencies

on:
  workflow_dispatch:
    inputs:
      exact-prod:
        default: false
        description: Exact version for production dependencies
        required: true
        type: boolean

jobs:
  bump-dependencies:
    name: Bump dependencies
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Check out current
        uses: actions/checkout@v3

      - id: create-branch
        name: Create branch
        run: |
          BRANCH_NAME=bot/bump-deps/${{ github.run_number }}

          git checkout -b $BRANCH_NAME
          echo branch-name=$BRANCH_NAME >> $GITHUB_OUTPUT

      - env:
          BUMP_DEV_OPTIONS: ''
          BUMP_PROD_OPTIONS: ${{ inputs.exact-prod && '--save-exact' || '' }}
        run: npm run bump

      - id: get-changes
        name: Get changes
        run: |
          if [[ `git ls-files --deleted --modified --others | wc -l` -gt 0 ]]
          then
            echo has-changes=true >> $GITHUB_OUTPUT
          fi

      - if: ${{ steps.get-changes.outputs.has-changes == 'true' }}
        name: Commit and push
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"

          git commit -a -m "Bump dependencies"
          git push -u origin ${{ steps.create-branch.outputs.branch-name }}

          echo Branch created at [\`${{ steps.create-branch.outputs.branch-name }}\`]\(${{ github.server }}/${{ github.repository }}/compare/${{ steps.create-branch.outputs.branch-name }}?expand=1\). >> $GITHUB_STEP_SUMMARY

      - env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ steps.get-changes.outputs.has-changes == 'true' }}
        name: Create pull request
        run: |
          URL=`gh pr create --fill --repo ${{ github.repository }} || true` >> $GITHUB_OUTPUT

          if [[ ! -z "$URL" ]]
          then
            echo Pull request created at $URL. >> $GITHUB_STEP_SUMMARY
          fi
