name: Set up scaffold

on:
  push:
    branches: ['main']

jobs:
  setup:
    if: ${{ github.run_number == 1 && github.repository != 'compulim/template-react-esbuild' }}
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"

      - name: Show README.scaffold.md
        run: |
          mv README.scaffold.md README.md
          git add --all
          git commit --message "Showing README.scaffold.md"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}

      - id: npm-install
        name: Run `npm install`
        run: |
          npm install --save react react-dom
          npm install --save-dev concurrently esbuild eslint eslint-plugin-prettier eslint-plugin-react typescript @types/react @types/react-dom @typescript-eslint/eslint-plugin @typescript-eslint/parser
          echo react-version=`npm ls react --json | jq -r '.dependencies.react.version'` > $GITHUB_OUTPUT

      - name: Set React version in `.eslintrc.react.yml` to ${{ steps.npm-install.outputs.react-version }}
        run: |
          docker run -i --rm mikefarah/yq '.settings.react.version = "${{ steps.npm-install.outputs.react-version }}"' < ./.eslintrc.react.yml > ./.eslintrc.react.yml.tmp
          mv .eslintrc.react.yml.tmp .eslintrc.react.yml
          ls .eslintrc.react.yml

      - name: Run `npm audit fix`
        continue-on-error: true
        run: npm audit fix

      - name: Show README.post.md
        run: mv README.post.md README.md

      - name: Commit and push
        run: |
          rm .github/workflows/set-up-scaffold.yml
          git add --all
          git commit --message "Initial `template-react-esbuild` scaffold"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}
